require('dotenv').config();
const path=require('node:path');const fs=require('node:fs');const crypto=require('node:crypto');
const express=require('express');const session=require('express-session');const MongoStore=require('connect-mongo');const {MongoClient,ObjectId,GridFSBucket}=require('mongodb');const bcrypt=require('bcryptjs');const helmet=require('helmet');const multer=require('multer');
const {validateReport,canAccess}=require('./validation');
function accountsFromEnv(){
 let rows;try{rows=JSON.parse(process.env.ACCOUNTS_JSON)}catch{throw Error('Set ACCOUNTS_JSON to the supplied private configuration.');}
 if(!Array.isArray(rows)||!rows.length||!rows.some(a=>a.role==='admin'))throw Error('Account configuration requires an administrator.');
 const m=new Map();for(const a of rows){if(!/^[a-z0-9.]+$/.test(a.username)||!['admin','campus'].includes(a.role)||typeof a.campus!=='string'||!/^\$2[aby]\$/.test(a.passwordHash)||m.has(a.username))throw Error('Invalid account configuration.');m.set(a.username,{...a,fingerprint:crypto.createHash('sha256').update(a.passwordHash).digest('hex')});}return m;
}
function createApp({db,client,accounts,production,sessionStore}){
 const app=express();const bucket=new GridFSBucket(db,{bucketName:'uploads'});const reports=db.collection('reports');
 app.disable('x-powered-by');app.set('trust proxy',1);
 app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'", "'sha256-7xL4SMbfobnHQ+4a9JgJE2GEb/3hJA5REoub7iaT8tI='"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'blob:','data:'],connectSrc:["'self'"],objectSrc:["'none'"],formAction:["'self'"],upgradeInsecureRequests:production?[]:null}}}));
 app.use((req,res,next)=>{if(production&&!req.secure)return res.redirect(308,(req.hostname==='simfoni.uitm-alumni.com'?'https://simfoni.uitm-alumni.com':'https://uitm-alumni.com')+req.originalUrl);next();});
 app.use(express.json({limit:'512kb'}));
 app.use(session({name:'ican.sid',secret:process.env.SESSION_SECRET,resave:false,saveUninitialized:false,store:sessionStore||MongoStore.create({clientPromise:Promise.resolve(client),dbName:'uitm_alumni',collectionName:'sessions',ttl:28800}),cookie:{httpOnly:true,secure:production,sameSite:'lax',maxAge:8*60*60*1000}}));
 app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!req.session.csrf)req.session.csrf=crypto.randomBytes(32).toString('hex');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.get('X-CSRF-Token')!==req.session.csrf)return res.status(403).json({error:'Session expired. Refresh and try again.'});next();});
 const publicUser=a=>({username:a.username,role:a.role,campus:a.campus,name:a.name||a.campus});
 function user(req){const a=accounts.get(req.session.username);return a&&a.fingerprint===req.session.fingerprint?a:null;}
 function auth(req,res,next){req.user=user(req);if(!req.user)return res.status(401).json({error:'Please sign in.'});next();}
 function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Administrator access required.'});next();}
 app.get('/api/auth/session',(req,res)=>res.json({user:user(req)?publicUser(user(req)):null,csrf:req.session.csrf}));
 app.post('/api/auth/login',async(req,res)=>{
  const username=typeof req.body.username==='string'?req.body.username.trim().toLowerCase():'';const password=req.body.password;
  if(typeof password!=='string'||password.length>200||username.length>100)return res.status(400).json({error:'Invalid login.'});
  const slot=Math.floor(Date.now()/900000);for(const key of ['ip:'+req.ip,'user:'+username]){const id=crypto.createHash('sha256').update(key+':'+slot).digest('hex');const count=await db.collection('login_attempts').findOneAndUpdate({_id:id},{$inc:{count:1},$setOnInsert:{expiresAt:new Date(Date.now()+1800000)}},{upsert:true,returnDocument:'after'});if(count.count>(key.startsWith('ip:')?60:15))return res.status(429).json({error:'Too many login attempts. Try again in 15 minutes.'});}
  const a=accounts.get(username);const hash=a?.passwordHash||[...accounts.values()][0].passwordHash;const valid=await bcrypt.compare(password,hash);
  if(!a||!valid)return res.status(401).json({error:'Incorrect username or password.'});
  await new Promise((ok,no)=>req.session.regenerate(e=>e?no(e):ok()));req.session.username=a.username;req.session.fingerprint=a.fingerprint;req.session.csrf=crypto.randomBytes(32).toString('hex');await new Promise((ok,no)=>req.session.save(e=>e?no(e):ok()));res.json({user:publicUser(a),csrf:req.session.csrf});
 });
 app.post('/api/auth/logout',auth,async(req,res)=>{await new Promise((ok,no)=>req.session.destroy(e=>e?no(e):ok()));res.clearCookie('ican.sid',{httpOnly:true,secure:production,sameSite:'lax'});res.json({ok:true});});
 app.get('/api/health',(req,res)=>res.json({ok:true,database:db.databaseName}));
 app.use('/api/reports',auth);
 app.get('/api/reports',async(req,res)=>{const filter=req.user.role==='admin'?{}:{owner:req.user.username};const list=await reports.find(filter,{projection:{data:1,kind:1,campus:1,owner:1,status:1,updatedAt:1,version:1}}).sort({updatedAt:-1}).limit(1000).toArray();res.json({reports:list});});
 async function load(req,res,next){if(!/^[a-f\d]{24}$/i.test(req.params.id))return res.status(404).json({error:'Report not found.'});req.report=await reports.findOne({_id:new ObjectId(req.params.id)});if(!canAccess(req.user,req.report))return res.status(404).json({error:'Report not found.'});next();}
 app.post('/api/reports',async(req,res)=>{let clean;try{clean=validateReport(req.body,req.body.submit===true)}catch(e){return res.status(400).json({error:e.message})}const now=new Date();const record={...clean,owner:req.user.username,campus:req.user.campus,status:req.body.submit===true?'submitted':'draft',createdAt:now,updatedAt:now,version:1,reviewComment:'',reviews:[]};const r=await reports.insertOne(record);res.status(201).json({...record,_id:r.insertedId});});
 app.get('/api/reports/:id',load,async(req,res)=>{const files=await bucket.find({'metadata.reportId':req.report._id.toString()}).toArray();res.json({...req.report,files:files.map(f=>({id:f._id,name:f.filename,size:f.length,...f.metadata}))});});
 app.put('/api/reports/:id',load,async(req,res)=>{if(req.report.owner!==req.user.username)return res.status(403).json({error:'Only the owning account can edit this report.'});if(req.report.status==='accepted')return res.status(409).json({error:'Accepted reports are locked. Ask Aliana to request a revision.'});if(req.body.kind!==req.report.kind)return res.status(400).json({error:'Report type cannot be changed.'});let clean;try{clean=validateReport(req.body,req.body.submit===true)}catch(e){return res.status(400).json({error:e.message})}const r=await reports.findOneAndUpdate({_id:req.report._id,version:req.body.version},{$set:{...clean,status:req.body.submit===true?'submitted':'draft',updatedAt:new Date()},$inc:{version:1}},{returnDocument:'after'});if(!r)return res.status(409).json({error:'This report changed in another tab. Reopen it before editing.'});res.json(r);});
 app.post('/api/reports/:id/review',admin,load,async(req,res)=>{const {status,comment,version}=req.body;if(!['accepted','revision_requested'].includes(status)||typeof comment!=='string'||comment.length>10000)return res.status(400).json({error:'Invalid review.'});if(status==='revision_requested'&&!comment.trim())return res.status(400).json({error:'Add a comment explaining the requested revision.'});if(req.report.status==='draft')return res.status(409).json({error:'This report has not been submitted.'});const review={status,comment:comment.trim(),by:req.user.username,at:new Date()};const r=await reports.findOneAndUpdate({_id:req.report._id,version},{$set:{status,reviewComment:review.comment,updatedAt:new Date()},$push:{reviews:review},$inc:{version:1}},{returnDocument:'after'});if(!r)return res.status(409).json({error:'Report changed. Reopen before reviewing.'});res.json(r);});
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:1,fields:3,fieldSize:10000}}).single('file');
 app.post('/api/reports/:id/files',load,(req,res,next)=>{if(req.user.username!==req.report.owner||req.report.status==='accepted')return res.status(403).json({error:'You cannot change files on this report.'});upload(req,res,next)},async(req,res)=>{
  const kind=req.body.kind;const caption=req.body.caption||'';if(!req.file||!['photo','supporting','financial'].includes(kind)||caption.length>2000)return res.status(400).json({error:'Choose a valid file and category.'});
  if(await db.collection('uploads.files').countDocuments({'metadata.reportId':req.params.id})>=40)return res.status(400).json({error:'Maximum 40 files per report.'});
  const {fileTypeFromBuffer}=await import('file-type');const type=await fileTypeFromBuffer(req.file.buffer);
  const images=['image/jpeg','image/png','image/webp'];const docs=[...images,'application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel'];
  if(!type||!(kind==='photo'?images:docs).includes(type.mime))return res.status(400).json({error:'Use JPG, PNG or WebP for photos; PDF, DOCX or XLSX for documents.'});
  const name=req.file.originalname.replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,120)||'document';const stream=bucket.openUploadStream(name,{metadata:{reportId:req.params.id,owner:req.user.username,kind,caption,contentType:type.mime}});await new Promise((ok,no)=>{stream.on('finish',ok);stream.on('error',no);stream.end(req.file.buffer)});res.status(201).json({id:stream.id,name,size:req.file.size,kind,caption,contentType:type.mime});
 });
 app.get('/api/files/:id',auth,async(req,res)=>{if(!/^[a-f\d]{24}$/i.test(req.params.id))return res.sendStatus(404);const id=new ObjectId(req.params.id);const f=await db.collection('uploads.files').findOne({_id:id});if(!f)return res.sendStatus(404);const r=await reports.findOne({_id:new ObjectId(f.metadata.reportId)});if(!canAccess(req.user,r))return res.sendStatus(404);res.set('Cache-Control','private, no-store');res.type(f.metadata.contentType);res.set('Content-Disposition',(f.metadata.kind==='photo'?'inline':'attachment')+'; filename="'+f.filename.replace(/["\r\n]/g,'_')+'"');const stream=bucket.openDownloadStream(id);stream.on('error',()=>{if(!res.headersSent)res.sendStatus(404);else res.destroy()});stream.pipe(res);});
 app.delete('/api/files/:id',auth,async(req,res)=>{if(!/^[a-f\d]{24}$/i.test(req.params.id))return res.sendStatus(404);const id=new ObjectId(req.params.id);const f=await db.collection('uploads.files').findOne({_id:id});if(!f)return res.sendStatus(404);const r=await reports.findOne({_id:new ObjectId(f.metadata.reportId)});if(!r||r.owner!==req.user.username||r.status==='accepted')return res.sendStatus(403);await bucket.delete(id);res.json({ok:true});});
 const manifest=require('./templates.json');
 app.get('/api/templates',auth,(req,res)=>res.json(manifest.map(t=>({...t,available:!!t.file&&fs.existsSync(path.join(__dirname,'templates',path.basename(t.file)))}))));
 app.get('/api/templates/:id',auth,(req,res)=>{const t=manifest.find(t=>t.id===req.params.id);if(!t?.file)return res.status(404).json({error:'Template not yet supplied.'});res.download(path.join(__dirname,'templates',path.basename(t.file)));});
 app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint not found.'}));
 app.get('/',(req,res,next)=>{if(req.hostname==='simfoni.uitm-alumni.com')return res.sendFile(path.join(__dirname,'../public/simfoni.html'));next();});
 app.use(express.static(path.join(__dirname,'../public'),{index:'index.html'}));
 app.use((err,req,res,next)=>{console.error('Request failed:',err.name,err.code||'');if(res.headersSent)return next(err);res.status(err instanceof multer.MulterError?400:500).json({error:err instanceof multer.MulterError?'Upload exceeds the 10 MB limit or contains unexpected fields.':'Request failed. Please try again.'});});
 return app;
}
async function main(){for(const k of ['MONGODB_URI','SESSION_SECRET','ACCOUNTS_JSON'])if(!process.env[k])throw Error('Missing Heroku Config Var: '+k);if(process.env.SESSION_SECRET.length<32)throw Error('SESSION_SECRET must have at least 32 characters.');const accounts=accountsFromEnv();const client=new MongoClient(process.env.MONGODB_URI,{maxPoolSize:10,serverSelectionTimeoutMS:15000});await client.connect();const db=client.db('uitm_alumni');await db.collection('login_attempts').createIndex({expiresAt:1},{expireAfterSeconds:0});await db.collection('reports').createIndex({owner:1,updatedAt:-1});const app=createApp({db,client,accounts,production:process.env.NODE_ENV==='production'});const server=app.listen(process.env.PORT||3000,()=>console.log('ICAN Alumni Reporting started; MongoDB connected.'));process.on('SIGTERM',()=>server.close(()=>client.close().finally(()=>process.exit(0))));}
if(require.main===module)main().catch(e=>{console.error('Startup failed:',e.name,e.code||'',/^(Missing|Set |Invalid account|Account config|SESSION_SECRET)/.test(e.message)?e.message:'Check MongoDB connection, credentials and Atlas network access.');process.exit(1)});
module.exports={createApp,accountsFromEnv};
